name: 🐞 Bug Report
description: Report a bug found in Edgemesh® Client.
title: "🐞 "
labels: ["bug", "triage"]
assignees:
  - supremetechnopriest
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
  - type: dropdown
    id: track
    attributes:
      label: Deployment Track
      description: What deployment track of our software are you running?
      options:
        - Stable (Production)
        - Canary (Edge)
        - Nightly (Development)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
  - type: dropdown
    id: devices
    attributes:
      label: What devices are you seeing the problem on?
      multiple: true
      options:
        - Desktop
        - Mobile
        - Tablet
        - Wearable
        - Other
  - type: input
    id: flareId
    attributes:
      label: What is the Flare ID for this bug report?
      description: "If you haven't generated a Flare, please do so with the [edgemesh.flare()](https://docs.edgemesh.com/client/reference/methods#flare) method or the [?em-controls](https://docs.edgemesh.com/client/developer/controls) search parameter."
      placeholder: "FlareID"
    validations:
      required: true
  - type: checkboxes
    id: verified
    attributes:
      label: Verification
      description: You have followed the [Support Guideline](https://docs.edgemesh.com/client/support/before) before submitting this bug.
      options:
        - label: I have verified that the bug is related to Edgemesh® Client
          required: true